
FROM node:14-alpine as build-stage
#RUN npm install -g @angular/cli@11
COPY . /app
WORKDIR /app
RUN npm install
ARG API_URL
#RUN node set_api_url.js
ARG configuration=production
RUN npm run build -- --output-path=./dist/out --configuration $configuration
CMD node set_api_url.js && ng serve --host 0.0.0.0 --disable-host-check

FROM nginx:1.24
COPY --from=build-stage /app/dist/out/ /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

