[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
incremental = false

[package]
name = "besim_gui_dioxus"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
reqwest = { version = "0.12", features = ["json"] }
console_error_panic_hook = "0.1"
tracing = "0.1.44"

# Web-only dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { version = "0.7", features = ["web", "logger", "router"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Location", "HtmlSelectElement", "HtmlInputElement", "HtmlCanvasElement", "CanvasRenderingContext2d"] }
gloo-timers = { version = "0.3", features = ["futures"] }
plotters = "0.3"
plotters-canvas = "0.3"

# Desktop-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus = { version = "0.7", features = ["desktop", "logger", "router"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tokio = { version = "1", features = ["time"] }
rust-embed = "8.11"
http = "1.4"
mime_guess = "2.0"

[[bin]]
name = "besim_gui_dioxus"
path = "src/web.rs"

[[bin]]
name = "besim_gui_dioxus_desktop"
path = "src/main.rs"
