[application]
name = "besim_gui_dioxus"
default_platform = "web"

[bundle]
identifier = "com.besmart.app"

[web]
app.title = "BeSMART"
# Serve static assets from the public folder
asset_dir = "public"

[web.watcher]
# Watch for changes in source files
watch_path = ["src"]

[web.resource]
style = []
script = []

[web.resource.dev]

[web.resource.release]
